// <auto-generated />
using System;
using Integrated_Construction_Management_System_ICMS.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Integrated_Construction_Management_System_ICMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Jobtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.BoqCondtionConsultant", b =>
                {
                    b.Property<int>("BoqCondtionConsultantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoqCondtionConsultantId"));

                    b.Property<string>("CondetionDetails")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ConsultantBoqId")
                        .HasColumnType("int");

                    b.HasKey("BoqCondtionConsultantId");

                    b.HasIndex("ConsultantBoqId")
                        .IsUnique();

                    b.ToTable("BoqCondtionConsultants");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.BoqCondtionEng", b =>
                {
                    b.Property<int>("BoqCondtionEngId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoqCondtionEngId"));

                    b.Property<string>("CondtionDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EngineerBoqID")
                        .HasColumnType("int");

                    b.HasKey("BoqCondtionEngId");

                    b.HasIndex("EngineerBoqID")
                        .IsUnique();

                    b.ToTable("BoqCondtionEngs");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ConsultantBoq", b =>
                {
                    b.Property<int>("ConsultantBoqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultantBoqId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("SiteEngineerId")
                        .HasColumnType("int");

                    b.Property<int>("SubConsultantID")
                        .HasColumnType("int");

                    b.Property<int>("Unite")
                        .HasColumnType("int");

                    b.HasKey("ConsultantBoqId");

                    b.HasIndex("ProjectID");

                    b.HasIndex("SiteEngineerId");

                    b.HasIndex("SubConsultantID");

                    b.ToTable("ConsultantBoqs");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.EngineerBoq", b =>
                {
                    b.Property<int>("EngineerBoqID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EngineerBoqID"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int?>("SiteEngineerId")
                        .HasColumnType("int");

                    b.Property<int>("StieEngineerId")
                        .HasColumnType("int");

                    b.Property<int>("SubContractorId")
                        .HasColumnType("int");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EngineerBoqID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("SiteEngineerId");

                    b.HasIndex("SubContractorId");

                    b.ToTable("EngineerBoqs");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.EngineerInvoice", b =>
                {
                    b.Property<int>("EngineerInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EngineerInvoiceId"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NewCompletion")
                        .HasColumnType("int");

                    b.Property<int>("OldCompletion")
                        .HasColumnType("int");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("SiteEngineerId")
                        .HasColumnType("int");

                    b.Property<int>("SubCosultantID")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int>("TotalInvoiceCost")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unite")
                        .HasColumnType("int");

                    b.Property<int?>("subConsultantSubCosultantID")
                        .HasColumnType("int");

                    b.HasKey("EngineerInvoiceId");

                    b.HasIndex("ProjectID");

                    b.HasIndex("SiteEngineerId");

                    b.HasIndex("subConsultantSubCosultantID");

                    b.ToTable("EngineerInvoices");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.Foreman", b =>
                {
                    b.Property<int>("ForemanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForemanId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("int");

                    b.HasKey("ForemanId");

                    b.HasIndex("ProjectManagerId")
                        .IsUnique();

                    b.ToTable("Foremen");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.FormanTasks", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ForemanId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskID");

                    b.HasIndex("ForemanId");

                    b.HasIndex("ProjectID");

                    b.ToTable("FormanTasks");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.GeneralDrowing", b =>
                {
                    b.Property<int>("GeneralDrowingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneralDrowingId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Dscription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("SubCosultantID")
                        .HasColumnType("int");

                    b.Property<int?>("subConsultantSubCosultantID")
                        .HasColumnType("int");

                    b.HasKey("GeneralDrowingId");

                    b.HasIndex("ProjectID");

                    b.HasIndex("subConsultantSubCosultantID");

                    b.ToTable("GeneralDrowings");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.MainClient", b =>
                {
                    b.Property<int>("MainClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MainClientID"));

                    b.Property<string>("MainClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MainClientNationalId")
                        .HasColumnType("int");

                    b.Property<int>("MainClientPhone")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.HasKey("MainClientID");

                    b.ToTable("MainClient");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.MainConsultant", b =>
                {
                    b.Property<int>("MaincosultantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaincosultantID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainCosultantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("int");

                    b.HasKey("MaincosultantID");

                    b.HasIndex("ProjectManagerId")
                        .IsUnique();

                    b.ToTable("MainConsultants");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaterialCount")
                        .HasColumnType("int");

                    b.Property<string>("MaterialDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectManagerID")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int?>("SubContractorId")
                        .HasColumnType("int");

                    b.HasKey("MaterialId");

                    b.HasIndex("ProjectManagerID");

                    b.HasIndex("StoreId");

                    b.HasIndex("SubContractorId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<int>("ForemanId")
                        .HasColumnType("int");

                    b.Property<int>("MainClientID")
                        .HasColumnType("int");

                    b.Property<string>("ProjectDescritpion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProjectLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("mainConsultanttMaincosultantID")
                        .HasColumnType("int");

                    b.HasKey("ProjectID");

                    b.HasIndex("ForemanId");

                    b.HasIndex("MainClientID");

                    b.HasIndex("ProjectManagerId");

                    b.HasIndex("mainConsultanttMaincosultantID");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ProjectContract", b =>
                {
                    b.Property<int>("ProjectContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectContractId"));

                    b.Property<string>("ClientCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientSignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractDetails")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EndContractIfs")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MainClientId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerSignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("int");

                    b.HasKey("ProjectContractId");

                    b.HasIndex("MainClientId")
                        .IsUnique();

                    b.HasIndex("ProjectID")
                        .IsUnique();

                    b.HasIndex("ProjectManagerId")
                        .IsUnique();

                    b.ToTable("ProjectContracts");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ProjectManager", b =>
                {
                    b.Property<int>("ProjectManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectManagerId"));

                    b.Property<string>("ProjectManagerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectManagerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProjectManagerPhone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("ProjectManagerId");

                    b.ToTable("ProjectManagers");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ProjectSiteEngineer", b =>
                {
                    b.Property<int>("ProjectSiteEngineerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectSiteEngineerID"));

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("SiteEngineerId")
                        .HasColumnType("int");

                    b.HasKey("ProjectSiteEngineerID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("SiteEngineerId");

                    b.ToTable("ProjectSiteEngineers");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ProjectSubConsultant", b =>
                {
                    b.Property<int>("ProjectSubConsultantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectSubConsultantId"));

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("SubCosultantID")
                        .HasColumnType("int");

                    b.Property<int?>("subConsultantSubCosultantID")
                        .HasColumnType("int");

                    b.HasKey("ProjectSubConsultantId");

                    b.HasIndex("ProjectID");

                    b.HasIndex("subConsultantSubCosultantID");

                    b.ToTable("ProjectSubConsultants");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ProjectSubContractor", b =>
                {
                    b.Property<int>("ProjectSubContractorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectSubContractorId"));

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("SubContractorId")
                        .HasColumnType("int");

                    b.HasKey("ProjectSubContractorId");

                    b.HasIndex("ProjectID");

                    b.HasIndex("SubContractorId");

                    b.ToTable("ProjectSubContractors");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ShopDrawing", b =>
                {
                    b.Property<int>("ShopDrawingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopDrawingId"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("SiteEngineerId")
                        .HasColumnType("int");

                    b.Property<int>("SubCosultantID")
                        .HasColumnType("int");

                    b.Property<int?>("subConsultantSubCosultantID")
                        .HasColumnType("int");

                    b.HasKey("ShopDrawingId");

                    b.HasIndex("ProjectID");

                    b.HasIndex("SiteEngineerId");

                    b.HasIndex("subConsultantSubCosultantID");

                    b.ToTable("ShopDrawings");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.SiteEngineer", b =>
                {
                    b.Property<int>("SiteEngineerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteEngineerId"));

                    b.Property<int>("ProjectManagerID")
                        .HasColumnType("int");

                    b.Property<string>("SiteEngineerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteEngineerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SiteEngineerPhone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("SiteEngineerSpeciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteEngineerId");

                    b.HasIndex("ProjectManagerID");

                    b.ToTable("SiteEngineer");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.Store", b =>
                {
                    b.Property<int>("StoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreID"));

                    b.Property<int>("ForemanId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("SiteEngineerId")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SubContractorId")
                        .HasColumnType("int");

                    b.HasKey("StoreID");

                    b.HasIndex("ForemanId");

                    b.HasIndex("ProjectID")
                        .IsUnique();

                    b.HasIndex("SiteEngineerId");

                    b.HasIndex("SubContractorId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.SubConstractorInvoice", b =>
                {
                    b.Property<int>("SubConstractorInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubConstractorInvoiceId"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NewCompletion")
                        .HasColumnType("int");

                    b.Property<int>("OldCompletion")
                        .HasColumnType("int");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("SiteEngineerId")
                        .HasColumnType("int");

                    b.Property<int>("SubContractorId")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int>("TotalInvoiceCost")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubConstractorInvoiceId");

                    b.HasIndex("ProjectID");

                    b.HasIndex("SiteEngineerId");

                    b.HasIndex("SubContractorId");

                    b.ToTable("SubConstractorInvoices");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.SubConsultant", b =>
                {
                    b.Property<int>("SubCosultantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCosultantID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MainCosultantID")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("ProjectManagerID")
                        .HasColumnType("int");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCosultantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("mainConsultantMaincosultantID")
                        .HasColumnType("int");

                    b.HasKey("SubCosultantID");

                    b.HasIndex("ProjectManagerID");

                    b.HasIndex("mainConsultantMaincosultantID");

                    b.ToTable("SubConsultant");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.SubContractor", b =>
                {
                    b.Property<int>("SubContractorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubContractorId"));

                    b.Property<string>("SubContractorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubContractorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubContractorPhone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("SubContractorSpeciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubContractorId");

                    b.ToTable("SubContractors");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.BoqCondtionConsultant", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.ConsultantBoq", "_consultantBoq")
                        .WithOne("boqCondtionConsultant")
                        .HasForeignKey("Integrated_Construction_Management_System_ICMS.Models.BoqCondtionConsultant", "ConsultantBoqId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("_consultantBoq");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.BoqCondtionEng", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.EngineerBoq", "engineerBoq")
                        .WithOne("boqCondtionEng")
                        .HasForeignKey("Integrated_Construction_Management_System_ICMS.Models.BoqCondtionEng", "EngineerBoqID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("engineerBoq");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ConsultantBoq", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Project", "project")
                        .WithMany("consultantBoq")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SiteEngineer", "siteEngineer")
                        .WithMany("consultantBoq")
                        .HasForeignKey("SiteEngineerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SubConsultant", "subConsultant")
                        .WithMany("consultantBoq")
                        .HasForeignKey("SubConsultantID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("project");

                    b.Navigation("siteEngineer");

                    b.Navigation("subConsultant");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.EngineerBoq", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Project", "project")
                        .WithMany("engineerBoq")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SiteEngineer", "siteEngineer")
                        .WithMany("engineerBoq")
                        .HasForeignKey("SiteEngineerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SubContractor", "subContractor")
                        .WithMany("engineerBoq")
                        .HasForeignKey("SubContractorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("project");

                    b.Navigation("siteEngineer");

                    b.Navigation("subContractor");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.EngineerInvoice", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Project", "project")
                        .WithMany("engineerInvoice")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SiteEngineer", "siteEngineer")
                        .WithMany("engineerInvoice")
                        .HasForeignKey("SiteEngineerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SubConsultant", "subConsultant")
                        .WithMany("engineerInvoice")
                        .HasForeignKey("subConsultantSubCosultantID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("project");

                    b.Navigation("siteEngineer");

                    b.Navigation("subConsultant");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.Foreman", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.ProjectManager", "projectManager")
                        .WithOne("foreman")
                        .HasForeignKey("Integrated_Construction_Management_System_ICMS.Models.Foreman", "ProjectManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("projectManager");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.FormanTasks", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Foreman", "foreman")
                        .WithMany("formanTasks")
                        .HasForeignKey("ForemanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Project", "project")
                        .WithMany("formanTasks")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("foreman");

                    b.Navigation("project");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.GeneralDrowing", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Project", "project")
                        .WithMany("generalDrowing")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SubConsultant", "subConsultant")
                        .WithMany("generalDrowing")
                        .HasForeignKey("subConsultantSubCosultantID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("project");

                    b.Navigation("subConsultant");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.MainConsultant", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.ProjectManager", "projectManager")
                        .WithOne("mainConsultant")
                        .HasForeignKey("Integrated_Construction_Management_System_ICMS.Models.MainConsultant", "ProjectManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("projectManager");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.Material", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.ProjectManager", "_ProjectManager")
                        .WithMany("material")
                        .HasForeignKey("ProjectManagerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Store", "Store")
                        .WithMany("Materials")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SubContractor", null)
                        .WithMany("materials")
                        .HasForeignKey("SubContractorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Store");

                    b.Navigation("_ProjectManager");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.Project", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Foreman", "foreman")
                        .WithMany("projects")
                        .HasForeignKey("ForemanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.MainClient", "mainClinet")
                        .WithMany("Projects")
                        .HasForeignKey("MainClientID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.ProjectManager", "_ProjectManager")
                        .WithMany("projects")
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.MainConsultant", "mainConsultantt")
                        .WithMany("projects")
                        .HasForeignKey("mainConsultanttMaincosultantID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("_ProjectManager");

                    b.Navigation("foreman");

                    b.Navigation("mainClinet");

                    b.Navigation("mainConsultantt");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ProjectContract", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.MainClient", "mainClient")
                        .WithOne("prjectContract")
                        .HasForeignKey("Integrated_Construction_Management_System_ICMS.Models.ProjectContract", "MainClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Project", "project")
                        .WithOne("prjectContract")
                        .HasForeignKey("Integrated_Construction_Management_System_ICMS.Models.ProjectContract", "ProjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.ProjectManager", "projectManager")
                        .WithOne("projectContract")
                        .HasForeignKey("Integrated_Construction_Management_System_ICMS.Models.ProjectContract", "ProjectManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("mainClient");

                    b.Navigation("project");

                    b.Navigation("projectManager");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ProjectSiteEngineer", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Project", "Project")
                        .WithMany("projectsiteEngineer")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SiteEngineer", "SiteEngineer")
                        .WithMany("projectSiteEngineers")
                        .HasForeignKey("SiteEngineerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("SiteEngineer");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ProjectSubConsultant", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Project", "project")
                        .WithMany("projectSubConsultant")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SubConsultant", "subConsultant")
                        .WithMany("projectSubConsultant")
                        .HasForeignKey("subConsultantSubCosultantID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("project");

                    b.Navigation("subConsultant");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ProjectSubContractor", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Project", "project")
                        .WithMany("projectSubContractors")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SubContractor", "subContractor")
                        .WithMany("projectSubContractors")
                        .HasForeignKey("SubContractorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("project");

                    b.Navigation("subContractor");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ShopDrawing", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Project", "project")
                        .WithMany("shopDrawing")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SiteEngineer", "siteEngineer")
                        .WithMany("shopDrawing")
                        .HasForeignKey("SiteEngineerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SubConsultant", "subConsultant")
                        .WithMany("shopDrawing")
                        .HasForeignKey("subConsultantSubCosultantID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("project");

                    b.Navigation("siteEngineer");

                    b.Navigation("subConsultant");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.SiteEngineer", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.ProjectManager", "_ProjectManager")
                        .WithMany("siteEngineer")
                        .HasForeignKey("ProjectManagerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("_ProjectManager");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.Store", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Foreman", "foreman")
                        .WithMany("store")
                        .HasForeignKey("ForemanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Project", "Project")
                        .WithOne("store")
                        .HasForeignKey("Integrated_Construction_Management_System_ICMS.Models.Store", "ProjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SiteEngineer", "siteEngineer")
                        .WithMany("stores")
                        .HasForeignKey("SiteEngineerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SubContractor", "subContractor")
                        .WithMany()
                        .HasForeignKey("SubContractorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("foreman");

                    b.Navigation("siteEngineer");

                    b.Navigation("subContractor");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.SubConstractorInvoice", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.Project", "project")
                        .WithMany("subConstractorInvoice")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SiteEngineer", "siteEngineer")
                        .WithMany("subConstractorInvoice")
                        .HasForeignKey("SiteEngineerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.SubContractor", "SubContractor")
                        .WithMany("subConstractorInvoice")
                        .HasForeignKey("SubContractorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SubContractor");

                    b.Navigation("project");

                    b.Navigation("siteEngineer");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.SubConsultant", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.ProjectManager", "_ProjectManager")
                        .WithMany("subConsultant")
                        .HasForeignKey("ProjectManagerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.MainConsultant", "mainConsultant")
                        .WithMany("subConsultant")
                        .HasForeignKey("mainConsultantMaincosultantID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("_ProjectManager");

                    b.Navigation("mainConsultant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Integrated_Construction_Management_System_ICMS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ConsultantBoq", b =>
                {
                    b.Navigation("boqCondtionConsultant");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.EngineerBoq", b =>
                {
                    b.Navigation("boqCondtionEng");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.Foreman", b =>
                {
                    b.Navigation("formanTasks");

                    b.Navigation("projects");

                    b.Navigation("store");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.MainClient", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("prjectContract");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.MainConsultant", b =>
                {
                    b.Navigation("projects");

                    b.Navigation("subConsultant");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.Project", b =>
                {
                    b.Navigation("consultantBoq");

                    b.Navigation("engineerBoq");

                    b.Navigation("engineerInvoice");

                    b.Navigation("formanTasks");

                    b.Navigation("generalDrowing");

                    b.Navigation("prjectContract");

                    b.Navigation("projectSubConsultant");

                    b.Navigation("projectSubContractors");

                    b.Navigation("projectsiteEngineer");

                    b.Navigation("shopDrawing");

                    b.Navigation("store");

                    b.Navigation("subConstractorInvoice");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.ProjectManager", b =>
                {
                    b.Navigation("foreman");

                    b.Navigation("mainConsultant");

                    b.Navigation("material");

                    b.Navigation("projectContract");

                    b.Navigation("projects");

                    b.Navigation("siteEngineer");

                    b.Navigation("subConsultant");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.SiteEngineer", b =>
                {
                    b.Navigation("consultantBoq");

                    b.Navigation("engineerBoq");

                    b.Navigation("engineerInvoice");

                    b.Navigation("projectSiteEngineers");

                    b.Navigation("shopDrawing");

                    b.Navigation("stores");

                    b.Navigation("subConstractorInvoice");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.Store", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.SubConsultant", b =>
                {
                    b.Navigation("consultantBoq");

                    b.Navigation("engineerInvoice");

                    b.Navigation("generalDrowing");

                    b.Navigation("projectSubConsultant");

                    b.Navigation("shopDrawing");
                });

            modelBuilder.Entity("Integrated_Construction_Management_System_ICMS.Models.SubContractor", b =>
                {
                    b.Navigation("engineerBoq");

                    b.Navigation("materials");

                    b.Navigation("projectSubContractors");

                    b.Navigation("subConstractorInvoice");
                });
#pragma warning restore 612, 618
        }
    }
}
